org.gradle.jvmargs=-Xmx2G

minecraft_version=26.2
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
loom_version=1.16.2

fabric_version=0.153.0+26.2

mod_version = 0.11.5+26.2
maven_group = foundationgames
archives_base_name = enhancedblockentities

modmenu_version=20.0.0-beta.4
sodium_version=mc26.2-0.9.1-beta.2-fabric
